services:
  app:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - LOCAL=false
    networks:
      - desafio-devops

networks:
  desafio-devops:
    driver: bridge
