[tool.poetry]
name = "emd-desafio-devops"
version = "0.1.0"
description = ""
authors = ["Escritório de Dados <escritoriodedados@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
flask = "^2.3.2"


[tool.poetry.group.dev.dependencies]
black = "^23.7.0"
flake8 = "^7.2.0"
pre-commit = "^4.2.0"
taskipy = "^1.14.1"
ruff = "^0.11.10"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.taskipy.tasks]
dev = "LOCAL=true ./start.sh"
prod = "LOCAL=false ./start.sh"
lint = "ruff check ."
format = "ruff format ."